hotels:
  urls:
    - "https://5f2be0b4ffc88500167b85a0.mockapi.io/suppliers/acme"
    - "https://5f2be0b4ffc88500167b85a0.mockapi.io/suppliers/patagonia"
    - "https://5f2be0b4ffc88500167b85a0.mockapi.io/suppliers/paperflies"

redis:
  host: "localhost"
  port: 6379
  db: 0

cronjob:
  interval: "*/30 * * * * *" # Every 30 seconds (for testing)

http:
  port: 8085
  host: "localhost" 